# The config recipe.
recipe: default.v1

# The assistant project unique identifier
assistant_id: 20241025-080545-angry-survey

# Configuration for Rasa NLU.
language: id

pipeline:
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: CountVectorsFeaturizer
  - name: SpacyNLP
    model: "xx_ent_wiki_sm"
  - name: EntitySynonymMapper
  - name: ResponseSelector
  - name: FallbackClassifier
    nlu_threshold: 0.3
    core_threshold: 0.3

# Configuration for Rasa Core.
policies:
- name: "MemoizationPolicy"
- name: "TEDPolicy"
  max_history: 5
- name: RulePolicy

cors:
- "*"
