name: Run Full Test with Railway Environment

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # Install dependencies
      - run: npm ci

      # Install Railway CLI
      - name: Install Railway CLI
        run: |
          curl -sSL https://railway.app/install.sh | sh

      # Set up Railway environment secrets
      - name: Set up Railway environment
        run: |
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> $GITHUB_ENV
          echo "RAILWAY_API_KEY=${{ secrets.RAILWAY_API_KEY }}" >> $GITHUB_ENV
          echo "RAILWAY_PROJECT_URL=${{ secrets.RAILWAY_PROJECT_URL }}" >> $GITHUB_ENV

      # Run tests (including white-box tests)
      - name: Run specific tests
        run: npm test

      # Run integration tests with Railway
      - name: Run integration tests with Railway
        run: |
          curl -X GET "${{ secrets.RAILWAY_PROJECT_URL }}/api/rasa/status"

      # Deploy to Railway after successful tests
      - name: Deploy to Railway
        run: |
          railway login --apiKey ${{ secrets.RAILWAY_API_KEY }}
          railway up --project ${{ secrets.RAILWAY_PROJECT_URL }}